apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-cdevents-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea-cdevents-adapter
  template:
    metadata:
      labels:
        app: gitea-cdevents-adapter
    spec:
      containers:
        - name: gitea-cdevents-adapter
          image: localhost/gitea-cdevents-adapter:latest
          imagePullPolicy: Never # for working in Kind
          ports:
            - containerPort: 8080
          env:
            - name: NATS_URL
              value: "nats://nats.nats.svc.cluster.local:4222"
            - name: LOG_LEVEL
              value: Debug
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: gitea-cdevents-adapter
spec:
  selector:
    app: gitea-cdevents-adapter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
